[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "freefont_ttf", "liberation_ttf", "noto-fonts"]

[phases.install]
cmds = ["npm run install:all"]

[phases.build]
cmds = ["npm run build"]

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
CHROMIUM_PATH = "/nix/var/nix/profiles/default/bin/chromium"
FONTCONFIG_PATH = "/nix/var/nix/profiles/default/etc/fonts"

[start]
cmd = "node server/index.js"
